
apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod

    spec:
      containers:
        - name: frontend-container
          image: quantiphiviramms/frontend:v2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
      volumes:
        - name: config-volume
          configMap:
            name: myconfigmap

